trigger:
- '*'

variables:
  webRepository: 'web'
  tag: '$(Build.BuildId)'

stages:  
- stage: 'Build'
  displayName: 'Build and push'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '6.x'

    steps:
    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        containerRegistry: 'Container Registry Connection'
        repository: '$(webRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags:
          $(tag) 


- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-20.04'
    
    variables:
    - group: Release
    steps:
    - task: AzureWebAppContainer@1
      inputs: 
          appName: $(WebAppName)
          azureSubscription: 'Resource Manager - Tailspin - Space Game'
          imageName: $(RegistryName)/$(webRepository):$(build.buildId)

